#!/usr/bin/env bash

# This script builds + deploys the website on my DigitalOcean VPS
# It assumes you've got SSH access, and a private key in ~/.ssh/do_dmoffat.com

echo "Deploying website..."

source .env

# Build and publish the nginx container
./build-publish-nginx

if [[ "$?" != "0" ]]; then
    echo "Failed to build + publish the nginx container."
    exit 1
fi

# Deploy it remotely
ssh -i ~/.ssh/do_dmoffat.com dmoffat.com -p 9999 /bin/bash << EOF
    echo "Authenticating with the registry"

    docker login -u danmofo@gmail.com -p $DIGITALOCEAN_API_KEY registry.digitalocean.com
    if [[ "$?" != "0" ]]; then
        echo "Failed to authenticate with container registry"
        exit 1
    fi

    echo "Pulling the container..."
    docker pull registry.digitalocean.com/dmoffat/dmoffat-nginx:latest
    if [[ "$?" != "0" ]]; then
        echo "Failed to pull container from container registry"
        exit 1
    fi
    
    echo "Killing existing container..."
    docker container kill dmoffat-nginx
    docker container rm dmoffat-nginx

    echo "Running new container..."
    docker run -d -p 80:8080 -p 443:8443 --name dmoffat-nginx registry.digitalocean.com/dmoffat/dmoffat-nginx
    if [[ "$?" != "0" ]]; then
        echo "Failed to start new container - website is currently down."
        exit 1
    fi
EOF